In [5]:
import numpy as np

In [7]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [8]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [10]:
np.full((3, 3), 6)

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [12]:
np.random.rand(2, 2)

array([[0.42479596, 0.61241728],
       [0.60261025, 0.99519646]])

In [13]:
np.random.randn(2, 2)

array([[ 0.34914589, -0.4689633 ],
       [-0.85806835, -0.62505576]])

In [25]:
arr_orginal = np.zeros((2, 2))

arr_view = arr_orginal.view()
arr_view[0][0] = 1
print(arr_view)
print(arr_orginal)

arr_copy = arr_orginal.copy()
arr_copy[1][1] = 5
print(arr_copy)
print(arr_orginal)

[[1. 0.]
 [0. 0.]]
[[1. 0.]
 [0. 0.]]
[[1. 0.]
 [0. 5.]]
[[1. 0.]
 [0. 0.]]
